# This is a basic workflow to help you get started with Actions

name: Travis CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  language: dart
    dart:
      - stable
    script:
      - pub get --packages-dir
      - pub run test

- name: Codecov Action
  uses: Atrox/codecov-action@v0.1.3
